---
defaults:
  client_id: 'monte_agent'
  client_secret: '2VoONsTTvGCryUrTxMY0'
  name: 'test-agent'
  reporting_period: 5
  enable_ssl: false
environments:
  production:
    auth_url: 'https://localhost:7049'
    api_url: 'https://localhost:7048'
    enable_ssl: true
  development:
    auth_url: 'https://localhost:7049'
    api_url: 'https://localhost:7048'
