---
defaults:
  client_id: "monte_agent"
  client_secret: "2VoONsTTvGCryUrTxMY0"
  name: 
  reporting_period: 1
  disable_ssl: true 
environments:
  production:
    auth_url: 'https://localhost:7049'
    api_url: 'https://localhost:7048'
    disable_ssl: false
  development:
    auth_url: 'https://localhost:7049'
    api_url: 'https://localhost:7048'
  docker: 
    auth_url: 'https://localhost:7049'
    api_url: 'https://localhost:7048'
